### ISSUE TITLE
error: error in 'egg_base' option: 'elastool' does not exist or is not a directory

### ISSUE THREAD

**Issue by jucego333** [zhongliliu/elastool#1]
Dear Dr

I have been trying to install your package on different computers and have been facing the same issue when i try to run the "setup.py file"

(base) jucego333@...........:~/elastol$ python setup.py install
running install
/home/jucego333/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/jucego333/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
error: error in 'egg_base' option: 'elastool' does not exist or is not a directory

**Comment by gmp007** [comment]
Sorry, this might have skipped me. Let me know if you still need help with this.
