### ISSUE TITLE
Error in computation of elastic constant of Cu 

### ISSUE THREAD

**Issue by someshb1** [zhongliliu/elastool#6]
Dear elastool developers,
I tried to do example "Cu_highT" but I got the following error. I have not change anything in the elastool.in file except the path of POTCARs and vasp run command.

Traceback (most recent call last):
  File "/home/lus03/joydipta/.local/bin/elastool", line 312, in <module>
    elastic_constants_dict,elastic_tensor, SEDF_values = calc_elastic_constants(pos_optimized, latt_system, {}, stress_set_dict,dimensional, plot=plotparameters[0])
IndexError: list index out of range
---------
Following lines are written in the log file.

Reading controlling parameters from elastool.in...

Calculating stresses using the OHESS strain matrices...
strain = -0.060

Fitting the first-order function to the collected 
stress-strain data according to Hooke's law...
---------
Thank you for your guidance.

**Comment by gmp007** [comment]
That elastool.in is for the very first version. Please look at the code website for details. Quick fix, follow these steps.1. pip uninstall elastool2. pip install -U elastool3. Then in the directory of your calculation, first remove elastool.in and then run elastool -0 and go from there. On Mar 25, 2024, at 11:08 PM, someshb1 ***@***.***> wrote:﻿
Dear elastool developers,
I tried to do example "Cu_highT" but I got the following error. I have not change anything in the elastool.in file except the path of POTCARs and vasp run command.
Traceback (most recent call last):
File "/home/lus03/joydipta/.local/bin/elastool", line 312, in 
elastic_constants_dict,elastic_tensor, SEDF_values = calc_elastic_constants(pos_optimized, latt_system, {}, stress_set_dict,dimensional, plot=plotparameters[0])
IndexError: list index out of range
Following lines are written in the log file.
Reading controlling parameters from elastool.in...
Calculating stresses using the OHESS strain matrices...
strain = -0.060
Fitting the first-order function to the collected
stress-strain data according to Hooke's law...
Thank you for your guidance.

**Comment by someshb1** [comment]
I am using elastool 3.5 which I have installed using pip.

**Comment by gmp007** [comment]
As I already explained to you. The elastool.in, which is the input file is the old version. Please follow the steps I provided and consult the code websiteOn Mar 26, 2024, at 4:20 AM, someshb1 ***@***.***> wrote:﻿
I am using elastool 3.5 which I have installed using pip.
