### ISSUE TITLE
Investigate the Impact of Pressure and Strain on Formation Enthalpy in elastool.

### ISSUE THREAD

**Issue by hongyi-zhao** [zhongliliu/elastool#7]
Hello elastool developer,

I have specific questions regarding the influence of pressure (a) and strain (b) on the formation enthalpy. I'm not sure whether elastool has the feature for such calculation and analysis. 

Thank you very much for your tips and hints.

Best regards,
Zhao

**Comment by gmp007** [comment]
Hi Zhao,
It is not currently implemented in ElasTool, but it is pretty
straightforward if it is a feature you want. You'll need sizeable
stress/strain to do a proper derivative.

**Comment by hongyi-zhao** [comment]
Hi @gmp007, 

Thank you for your comments. Do you agree with the following formula to [calculate the enthalpy of formation?](https://mattermodeling.stackexchange.com/questions/4260/how-to-calculate-the-enthalpy-of-formation)

![image](https://github.com/zhongliliu/elastool/assets/11155854/0274ff85-f866-4069-af1c-6cf9c8712426)

**Comment by gmp007** [comment]
That looks correct to me. Think about formation enthalpy as formation
energy at 0 K. Broadly defined, formation enthalpy is temperature-dependent.

**Comment by hongyi-zhao** [comment]
> Broadly defined, formation enthalpy is temperature-dependent.

In general, however, this form of temperature-dependent should be complex and difficult to calculate, at least within the framework of the DFT.

**Comment by gmp007** [comment]
Yes, no temperature in DFT, but one can incorporate temperature in various
forms, e.g., QHA.

**Comment by hongyi-zhao** [comment]
About the QHA, I recently noticed the question asked [here](https://github.com/materialsproject/pymatgen/discussions/3608) with the topic "Debye temperature calculation formula in the QuasiharmonicDebyeApprox class":

![image](https://github.com/zhongliliu/elastool/assets/11155854/67a8bc6f-3821-4021-b499-db6144422fef)

As for the above question, I have tried to think and understand it, but finally I still do not understand how the circle 1 and circle 2 shown in the above figure correspond. I'm not sure if you'd be able to give some hints and ideas on this question.

**Comment by gmp007** [comment]
Hi Zhongliliu,
I cannot comment on whether it is correct or not. One has to fully derive
it to be sure. QHA is just adding the vibrational free energy of the nuclei
to the zero-temperature free energy from DFT. I am not sure what you need
this formula for to start with. If you need Debye temperature, ElasTool
provides it using the sound velocity, which corresponds to the acoustic
phonon in terms of vibrational properties.

**Comment by zhongliliu** [comment]
Hi Chinedu,

Elastool does not use QHA. The formation enthalpy can be obtained using other code, such as PhaseGO which deals with QHA.


Zhongli













At 2024-04-13 10:00:28, "gmp007" ***@***.***> wrote:

Hi Zhongliliu,
I cannot comment on whether it is correct or not. One has to fully derive
it to be sure. QHA is just adding the vibrational free energy of the nuclei
to the zero-temperature free energy from DFT. I am not sure what you need
this formula for to start with. If you need Debye temperature, ElasTool
provides it using the sound velocity, which corresponds to the acoustic
phonon in terms of vibrational properties.

**Comment by gmp007** [comment]
I want to believe this is taken care of. I am going to close this thread. Let us know if you need further assistance.
