### ISSUE TITLE
Obtain the bulk modulus's pressure derivative (B') with the help of elastool.

### ISSUE THREAD

**Issue by hongyi-zhao** [zhongliliu/elastool#9]
Can I obtain the bulk modulus’s pressure derivative (B') with the help of elastool, as done [here](http://dx.doi.org/10.1016/j.rinp.2012.06.001) in table 1?

[Structural and electronic properties of the Laves phase based on rare earth type BaM2 (M = Rh, Pd, Pt).pdf](https://github.com/user-attachments/files/15749933/Structural.and.electronic.properties.of.the.Laves.phase.based.on.rare.earth.type.BaM2.M.Rh.Pd.Pt.pdf)

For example, pymatgen can do the trick as follows:

```python
In [1]: from pymatgen.analysis.eos import EOS
   ...: 
   ...: # 假设你有体积和能量的数据
   ...: volumes = [10.0, 10.5, 11.0, 11.5, 12.0]  # 体积数据
   ...: energies = [-10.0, -10.5, -11.0, -11.4, -11.3]  # 能量数据
   ...: 
   ...: # 创建EOS对象，选择一个状态方程模型（如Murnaghan）
   ...: eos = EOS(eos_name='murnaghan')
   ...: 
   ...: # 拟合数据
   ...: eos_fit = eos.fit(volumes, energies)
   ...: 
   ...: # 提取体模量及其压力导数
   ...: bulk_modulus = eos_fit.b0  # 体模量
   ...: bulk_modulus_prime = eos_fit.b1  # 体模量的压力导数
   ...: 
   ...: print(f"体模量 (B0): {bulk_modulus} GPa")
   ...: print(f"体模量的压力导数 (B0'): {bulk_modulus_prime}")
体模量 (B0): 41.44689131996187 GPa
体模量的压力导数 (B0'): -40.72387311271952
```

Regards,
Zhao

**Comment by gmp007** [comment]
No, this has not been implemented in elastool.
